general:
  prefix_name: rdmc01 # this is a prefix for creating unique naming in Azure.

resource_group:
  name: dev-azure-ai-document-search-rg
  location: brazilsouth

azurerm_search_service:
  name: dev-azure-search-service
  sku: free

azurerm_storage_account:
  name: devazuresearchsa

azurerm_storage_container:
  name: dev-docs
  access_type: container

# azurerm_cognitive_account_document_intelligence:
#   name: russ-dev-azure-document-intelligence
