resource_group:
  name: russ-dev-azure-ai-document-search-rg
  location: brazilsouth

azurerm_search_service:
  name: russ-dev-azure-search-service

azurerm_storage_account:
  name: russdevazuresearchsa

azurerm_storage_container:
  name: russ-dev-docs

# azurerm_cognitive_account_document_intelligence:
#   name: russ-dev-azure-document-intelligence
