general:
  prefix_name: rdmc01 # this is a prefix for creating unique naming in Azure.

resource_group:
  name: prod-azure-ai-document-search-rg
  location: brazilsouth

azurerm_search_service:
  name: prod-azure-search-service
  sku: free

azurerm_storage_account:
  name: prodazuresearchsa

azurerm_storage_container:
  name: prod-docs
  access_type: container
